import type { Expense, RecurringExpense } from './types';
import { type LucideIcon, Mail, PenLine, RefreshCw, Camera } from 'lucide-react';

// Extended type with notes and tags for demo purposes
export interface DemoExpense extends Expense {
  demo_notes?: string;
  demo_tags?: string[];
}

export const DEMO_EXPENSES: DemoExpense[] = [
  // Cleaning
  { id: 'exp-1', user_id: 'demo', property_id: '1', category: 'cleaning', description: 'Standard turnover clean', amount: 150, date: '2026-02-03', frequency: 'per-turnover', vendor: 'CleanBnB LA', is_recurring: true, recurring_expense_id: 'rec-1', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-03T00:00:00Z', updated_at: '2026-02-03T00:00:00Z', paid_at: '2026-02-03T00:00:00Z', demo_tags: ['recurring'] },
  { id: 'exp-2', user_id: 'demo', property_id: '3', category: 'cleaning', description: 'Standard turnover clean', amount: 150, date: '2026-02-05', frequency: 'per-turnover', vendor: 'Desert Sparkle Cleaning', is_recurring: true, recurring_expense_id: 'rec-2', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-05T00:00:00Z', updated_at: '2026-02-05T00:00:00Z', paid_at: '2026-02-05T00:00:00Z', demo_tags: ['recurring'] },
  { id: 'exp-3', user_id: 'demo', property_id: '1', category: 'cleaning', description: 'Deep clean — quarterly', amount: 250, date: '2026-01-15', frequency: 'quarterly', vendor: 'CleanBnB LA', is_recurring: true, recurring_expense_id: 'rec-3', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-15T00:00:00Z', updated_at: '2026-01-15T00:00:00Z', paid_at: '2026-01-15T00:00:00Z', demo_tags: ['recurring', 'tax-deductible'] },

  // Insurance
  { id: 'exp-4', user_id: 'demo', property_id: '1', category: 'insurance', description: 'Short-term rental liability policy', amount: 1200, date: '2026-01-10', frequency: 'annual', vendor: 'Proper Insurance', is_recurring: true, recurring_expense_id: 'rec-4', source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-10T00:00:00Z', updated_at: '2026-01-10T00:00:00Z', paid_at: '2026-01-10T00:00:00Z', demo_tags: ['tax-deductible', 'recurring'] },
  { id: 'exp-5', user_id: 'demo', property_id: '3', category: 'insurance', description: 'Property insurance — cabin', amount: 1200, date: '2026-01-10', frequency: 'annual', vendor: 'CBIZ Insurance', is_recurring: true, recurring_expense_id: 'rec-5', source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-10T00:00:00Z', updated_at: '2026-01-10T00:00:00Z', paid_at: '2026-01-10T00:00:00Z', demo_notes: 'Negotiated 10% discount', demo_tags: ['tax-deductible', 'recurring'] },

  // Maintenance
  { id: 'exp-6', user_id: 'demo', property_id: '2', category: 'maintenance', description: 'Plumber — kitchen faucet leak', amount: 85, date: '2026-01-22', frequency: 'one-time', vendor: 'Mike\'s Plumbing', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: '/receipts/plumber-receipt.jpg', utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-22T00:00:00Z', updated_at: '2026-01-22T00:00:00Z', paid_at: '2026-01-22T00:00:00Z', demo_tags: ['tax-deductible'] },
  { id: 'exp-7', user_id: 'demo', property_id: '1', category: 'maintenance', description: 'Lightbulb replacement (6 smart bulbs)', amount: 45, date: '2026-02-01', frequency: 'one-time', vendor: 'Amazon', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: '/receipts/amazon-receipt.jpg', utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z' },
  { id: 'exp-8', user_id: 'demo', property_id: '3', category: 'maintenance', description: 'HVAC service & filter replacement', amount: 320, date: '2026-01-28', frequency: 'one-time', vendor: 'Desert Air HVAC', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: '/receipts/hvac-receipt.jpg', utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-28T00:00:00Z', updated_at: '2026-01-28T00:00:00Z', paid_at: '2026-01-28T00:00:00Z', demo_notes: 'Guest broke the AC unit', demo_tags: ['emergency', 'reimbursable'] },

  // Mortgage / Rent
  { id: 'exp-9', user_id: 'demo', property_id: '1', category: 'mortgage', description: 'Monthly rent — Venice unit', amount: 3200, date: '2026-02-01', frequency: 'monthly', vendor: 'Venice Properties LLC', is_recurring: true, recurring_expense_id: 'rec-6', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z', demo_tags: ['recurring', 'tax-deductible'] },
  { id: 'exp-10', user_id: 'demo', property_id: '2', category: 'mortgage', description: 'Monthly rent — Silver Lake', amount: 3500, date: '2026-02-01', frequency: 'monthly', vendor: 'SL Realty Group', is_recurring: true, recurring_expense_id: 'rec-7', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z', demo_tags: ['recurring', 'tax-deductible'] },
  { id: 'exp-11', user_id: 'demo', property_id: '3', category: 'mortgage', description: 'Monthly rent — JT cabin', amount: 2800, date: '2026-02-01', frequency: 'monthly', vendor: 'Desert Homes Inc', is_recurring: true, recurring_expense_id: 'rec-8', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z', demo_tags: ['recurring', 'tax-deductible'] },

  // Supplies
  { id: 'exp-12', user_id: 'demo', property_id: '1', category: 'supplies', description: 'Toiletries restock — shampoo, soap, etc.', amount: 67, date: '2026-01-25', frequency: 'one-time', vendor: 'Costco', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: '/receipts/costco-receipt.jpg', utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-25T00:00:00Z', updated_at: '2026-01-25T00:00:00Z', paid_at: '2026-01-25T00:00:00Z', demo_tags: ['tax-deductible'] },
  { id: 'exp-13', user_id: 'demo', property_id: '3', category: 'supplies', description: 'Linen replacement — 2 queen sets', amount: 124, date: '2026-02-02', frequency: 'one-time', vendor: 'Amazon', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-02T00:00:00Z', updated_at: '2026-02-02T00:00:00Z', paid_at: '2026-02-02T00:00:00Z' },

  // Taxes
  { id: 'exp-14', user_id: 'demo', property_id: '1', category: 'taxes', description: 'TOT / lodging tax — Q4 2025', amount: 1850, date: '2026-01-31', frequency: 'quarterly', vendor: 'City of Los Angeles', is_recurring: true, recurring_expense_id: 'rec-9', source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-31T00:00:00Z', updated_at: '2026-01-31T00:00:00Z', paid_at: '2026-01-31T00:00:00Z', demo_tags: ['tax-deductible', 'recurring'] },

  // Management
  { id: 'exp-15', user_id: 'demo', property_id: '2', category: 'management', description: 'Co-host fee — February', amount: 450, date: '2026-02-01', frequency: 'monthly', vendor: 'Sarah (co-host)', is_recurring: true, recurring_expense_id: 'rec-10', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z', demo_tags: ['recurring', 'tax-deductible'] },

  // Subscription
  { id: 'exp-16', user_id: 'demo', property_id: '1', category: 'subscription', description: 'Hospitable PMS — monthly', amount: 29, date: '2026-02-01', frequency: 'monthly', vendor: 'Hospitable', is_recurring: true, recurring_expense_id: 'rec-11', source: 'recurring_auto', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: '2026-02-01T00:00:00Z', demo_tags: ['recurring'] },

  // Utilities (matching existing bill data as expenses)
  { id: 'exp-17', user_id: 'demo', property_id: '1', category: 'utility', description: 'Electric — LADWP', amount: 142.50, date: '2026-02-01', frequency: 'monthly', vendor: 'LADWP', is_recurring: true, recurring_expense_id: null, source: 'email_parse', status: 'pending', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z', paid_at: null, demo_tags: ['recurring'] },
  { id: 'exp-18', user_id: 'demo', property_id: '1', category: 'utility', description: 'Gas — SoCalGas', amount: 67.30, date: '2026-01-28', frequency: 'monthly', vendor: 'SoCalGas', is_recurring: true, recurring_expense_id: null, source: 'email_parse', status: 'overdue', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-28T00:00:00Z', updated_at: '2026-01-28T00:00:00Z', paid_at: null, demo_tags: ['recurring'] },
  { id: 'exp-19', user_id: 'demo', property_id: '2', category: 'utility', description: 'Electric — LADWP', amount: 198.00, date: '2026-02-05', frequency: 'monthly', vendor: 'LADWP', is_recurring: true, recurring_expense_id: null, source: 'email_parse', status: 'pending', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-05T00:00:00Z', updated_at: '2026-02-05T00:00:00Z', paid_at: null, demo_tags: ['recurring'] },
  { id: 'exp-20', user_id: 'demo', property_id: '2', category: 'utility', description: 'Internet — Spectrum', amount: 89.99, date: '2026-01-25', frequency: 'monthly', vendor: 'Spectrum', is_recurring: true, recurring_expense_id: null, source: 'email_parse', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-25T00:00:00Z', updated_at: '2026-01-25T00:00:00Z', paid_at: '2026-01-25T00:00:00Z', demo_tags: ['recurring'] },
  { id: 'exp-21', user_id: 'demo', property_id: '3', category: 'utility', description: 'Electric — SCE', amount: 210.75, date: '2026-02-03', frequency: 'monthly', vendor: 'SCE', is_recurring: true, recurring_expense_id: null, source: 'email_parse', status: 'pending', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-03T00:00:00Z', updated_at: '2026-02-03T00:00:00Z', paid_at: null, demo_tags: ['recurring'] },

  // DUPLICATE ENTRIES for demo purposes
  { id: 'exp-dup-1', user_id: 'demo', property_id: '1', category: 'cleaning', description: 'Standard turnover clean', amount: 150, date: '2026-02-03', frequency: 'per-turnover', vendor: 'CleanBnB LA', is_recurring: false, recurring_expense_id: null, source: 'manual', status: 'paid', payment_method: null, notes: null, receipt_url: null, utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-02-03T01:00:00Z', updated_at: '2026-02-03T01:00:00Z', paid_at: '2026-02-03T01:00:00Z' },
  { id: 'exp-dup-2', user_id: 'demo', property_id: '3', category: 'maintenance', description: 'HVAC service & filter replacement', amount: 320, date: '2026-01-29', frequency: 'one-time', vendor: 'Desert Air HVAC', is_recurring: false, recurring_expense_id: null, source: 'receipt_scan', status: 'paid', payment_method: null, notes: null, receipt_url: '/receipts/hvac-receipt-2.jpg', utility_account_id: null, billing_period_start: null, billing_period_end: null, due_date: null, raw_email_id: null, confidence_score: null, created_at: '2026-01-29T00:00:00Z', updated_at: '2026-01-29T00:00:00Z', paid_at: '2026-01-29T00:00:00Z', demo_notes: 'Emergency repair — weekend rate', demo_tags: ['emergency'] },
];

export const DEMO_RECURRING_EXPENSES: RecurringExpense[] = [
  { id: 'rec-1', user_id: 'demo', property_id: '1', category: 'cleaning', description: 'Standard turnover clean', amount: 150, frequency: 'per-turnover', vendor: 'CleanBnB LA', next_due_date: '2026-02-10', is_active: true, last_generated_date: '2026-02-03', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-03T00:00:00Z' },
  { id: 'rec-2', user_id: 'demo', property_id: '3', category: 'cleaning', description: 'Standard turnover clean', amount: 150, frequency: 'per-turnover', vendor: 'Desert Sparkle Cleaning', next_due_date: '2026-02-12', is_active: true, last_generated_date: '2026-02-05', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-05T00:00:00Z' },
  { id: 'rec-3', user_id: 'demo', property_id: '1', category: 'cleaning', description: 'Deep clean — quarterly', amount: 250, frequency: 'quarterly', vendor: 'CleanBnB LA', next_due_date: '2026-04-15', is_active: true, last_generated_date: '2026-01-15', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: 'rec-4', user_id: 'demo', property_id: '1', category: 'insurance', description: 'STR liability policy', amount: 1200, frequency: 'annual', vendor: 'Proper Insurance', next_due_date: '2027-01-10', is_active: true, last_generated_date: '2026-01-10', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-10T00:00:00Z' },
  { id: 'rec-5', user_id: 'demo', property_id: '3', category: 'insurance', description: 'Property insurance — cabin', amount: 1200, frequency: 'annual', vendor: 'CBIZ Insurance', next_due_date: '2027-01-10', is_active: true, last_generated_date: '2026-01-10', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-10T00:00:00Z' },
  { id: 'rec-6', user_id: 'demo', property_id: '1', category: 'mortgage', description: 'Monthly rent — Venice unit', amount: 3200, frequency: 'monthly', vendor: 'Venice Properties LLC', next_due_date: '2026-03-01', is_active: true, last_generated_date: '2026-02-01', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
  { id: 'rec-7', user_id: 'demo', property_id: '2', category: 'mortgage', description: 'Monthly rent — Silver Lake', amount: 3500, frequency: 'monthly', vendor: 'SL Realty Group', next_due_date: '2026-03-01', is_active: true, last_generated_date: '2026-02-01', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
  { id: 'rec-8', user_id: 'demo', property_id: '3', category: 'mortgage', description: 'Monthly rent — JT cabin', amount: 2800, frequency: 'monthly', vendor: 'Desert Homes Inc', next_due_date: '2026-03-01', is_active: true, last_generated_date: '2026-02-01', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
  { id: 'rec-9', user_id: 'demo', property_id: '1', category: 'taxes', description: 'TOT / lodging tax', amount: 1850, frequency: 'quarterly', vendor: 'City of Los Angeles', next_due_date: '2026-04-30', is_active: true, last_generated_date: '2026-01-31', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-31T00:00:00Z' },
  { id: 'rec-10', user_id: 'demo', property_id: '2', category: 'management', description: 'Co-host fee', amount: 450, frequency: 'monthly', vendor: 'Sarah (co-host)', next_due_date: '2026-03-01', is_active: true, last_generated_date: '2026-02-01', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
  { id: 'rec-11', user_id: 'demo', property_id: '1', category: 'subscription', description: 'Hospitable PMS', amount: 29, frequency: 'monthly', vendor: 'Hospitable', next_due_date: '2026-03-01', is_active: true, last_generated_date: '2026-02-01', notes: null, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-02-01T00:00:00Z' },
];

export function getExpensesForProperty(propertyId: string): DemoExpense[] {
  return DEMO_EXPENSES.filter(e => e.property_id === propertyId);
}

export function getExpensesByCategory(expenses: DemoExpense[]): Record<string, number> {
  const result: Record<string, number> = {};
  for (const e of expenses) {
    result[e.category] = (result[e.category] || 0) + e.amount;
  }
  return result;
}

export function getSourceIcon(source: DemoExpense['source']): LucideIcon {
  switch (source) {
    case 'email_parse': return Mail;
    case 'manual': return PenLine;
    case 'recurring_auto': return RefreshCw;
    case 'receipt_scan': return Camera;
    default: return PenLine;
  }
}

export function getSourceLabel(source: DemoExpense['source']): string {
  switch (source) {
    case 'email_parse': return 'Email';
    case 'manual': return 'Manual';
    case 'recurring_auto': return 'Recurring';
    case 'receipt_scan': return 'Receipt';
  }
}
